### PR TITLE
Merge dev with analytics fixes

### PR DESCRIPTION
**Pull request by tobiasrohloff**
@MrSerth please take care of the conflicts.

### CODE REVIEW

**Comment by MrSerth** [comment]
@tobiasrohloff I resolved the merge conflicts and successfully tested the general functionality in Firefox 52 ESR on Windows from a local `polymer serve`.

Unfortunately, some tests fail on my PR #44. As these are the same as on this PR (even one less), I think, I did not include a new bug specific on these tests with my merge. Please double-check the tests on Travis.

**Comment by tobiasrohloff** [comment]
Alright, thank you. No idea about the failing tests, but we're gonna fix that soon.

**Comment by soldag** [comment]
@tobiasrohloff @MrSerth Does anything speaks against merging this, as the tests are now working again?

**Comment by tobiasrohloff** [comment]
@soldag if your recently added commits and features are stable and ready for release, go for it :) afterwards, please also release a new version. I want to deploy it soon on openHPI.

**Comment by MrSerth** [comment]
@soldag There are no new URLs, we need to change. Go for it! :shipit:

**Pull request merged**
